### ISSUE TITLE
0.0.24: Groundnet version should be an integer, not a string

### ISSUE THREAD

**Issue by sfrsfrsfr** [Portree-Kid/flightgear-airports#95] opened 2020-09-05 06:48 UTC
i noticed the exported groundnet XML files contain this line:

  `<version>Sun, 30 Aug 2020 19:35:02 GMT by FlightgearAirports</version>`

But flightgear assumes `<version>` is an integer, not a string.
See flightgear/src/AIModel/AIFlightPlanCreate.cxx:

  if (gn->getVersion() == 1) {
        runwayNode = gn->findNearestNodeOnRunway(lastWptPos);
    } else {
        runwayNode = gn->findNearestNode(lastWptPos);
    }

Although it doesn't seem to be an issue right now i think the fga version string should better be put in a comment instead.
Addtionally it doesn't even mention the version of fga used :)

What about already uploaded/distributed groundnet files?

**Comment by Portree-Kid** [comment] 2020-10-02 12:02
This could be the cause for some erratic behaviour. I'll check what the correct file version should be

**Comment by Portree-Kid** [comment] 2020-10-05 18:27
Fixed in 0.0.26

**Closed by Portree-Kid** 2020-10-05 18:27 UTC
