### ISSUE TITLE
v0.0.21 Check does not complete

### ISSUE THREAD

**Issue by LGBudd** [Portree-Kid/flightgear-airports#80] opened 2020-07-23 20:48 UTC
Installed v0.0.21 after uninstalling v0.0.20. First thing was to perform a check of the groundnet I've been working on. However, it did not complete and I had to hit the "X" to close the app. I thought maybe if I made a change and saved before a check it would make a difference, but the behavior was the same.
This worked fine in v0.0.20. Are others experiencing this issue?

**Comment by Portree-Kid** [comment] 2020-07-24 05:19
Can't reproduce. Can you open the debugger and see if there is an error in the console? Click on settings and at the bottom there is a button

**Comment by LGBudd** [comment] 2020-07-25 02:29
`TypeError: Cannot read property 'eachLayer' of undefined
    at a.check (renderer.js:11)
    at a.showCheck (renderer.js:11)
    at W (renderer.js:1)
    at a.o (renderer.js:1)
    at W (renderer.js:1)
    at a.e.$emit (renderer.js:1)
    at a.click (renderer.js:11)
    at HTMLAnchorElement.<anonymous> (renderer.js:1)`

**Comment by Portree-Kid** [comment] 2020-07-27 05:32
Fixed in 0.0.22

**Closed by Portree-Kid** 2020-07-27 05:32 UTC
Labels: Check, MVP, bug
