### ISSUE TITLE
wrong parking stats

### ISSUE THREAD

**Issue by wkitty42** [Portree-Kid/flightgear-airports#26] opened 2020-07-04 15:29 UTC
i started with the current "parking only" KCLT ground net... i've added/edited ~91 parking places into it with full paths to all runways... when i start the tool at KCLT... click on the properties button and then the Statistics tab... it tells me there's only 12 parking positions but when i go to the Parking tab, i count ~91 different parking positions... yes, i'm sure there are at least 91 because it took me a while to put them all in ;)

**Comment by Portree-Kid** [comment] 2020-07-04 17:55
Duplicate of #27 Stats are only updated on scan not save.

**Closed** 2020-07-04 17:55 UTC
Labels: duplicate
